### ISSUE TITLE
Сформировать структуру основной комнаты(лабиринта)

### ISSUE THREAD

**Issue by Aramymo** [PAD1K/JameGam#12]
Основная комната оформлена как лабиринт(то есть тупиковые проходы), однако должно быть 4 выхода(вверх, вниз, влево, вправо карты).

**Comment by LadygaPavel** [comment]
![Image](https://github.com/PAD1K/JameGam/assets/83593908/14fa0635-88b3-4d2a-a9a7-dfed416475b2)
