### ISSUE TITLE
Реализовать ShootController

### ISSUE THREAD

**Issue by HozzyUwU** [PAD1K/JameGam#4]
Необходимо реализовать ShootController при использовании интерфейса IShoot. Кроме того требуется создать ObjectPool для пулей. Пули могут потребовать наличие дополнительного класса.

![Image](https://github.com/PAD1K/JameGam/assets/82671681/97a6b2ad-2512-474e-be14-8b62135847f5)

**Comment by Maler-front** [comment]
Ну ты и расписал, конечно)
